language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: fjsS6Zg70QjqJrqlI1LQ8/qTQmMZF1SLpA5ZosloSfcBGytJhWEYIRmzj0vddLHiWdIaAmcOMvjvWqY7nZhIkA9zMQypaqZrMDjMM0VDTif3dIzB+69wx44kprq+3KTkCeYfr05ES+xM4vqpzkvtdzdHN1NqKotMbPK6jV0ycVyUwyv4w3wsp4azvjX1MccDaQ+ktoq7R7d3vQXCcL3VbUrMemXfanUGt4XyHSd0Y6yOGzU9ucxhdNpRwqxb7EBpRMQO46OLjfM9fuIUUIfFo8bJsyyHM6WQnvWlQH9aQxCscTJCetWrvnyu86EfhDTYoBk5kYeJ3PLzfgaYj6xomwmYQeu/9iKcbTRJ/d8QiUGDywdFhOFPF6k2g/EChewWrpACjGqF50h5VUbAUtvd5wmOIwfXlK5Cz8Cg8UqZ/z1iCoSJVztMemJNf7/mmxd6SaJ8yUj/hSHR81P05Gjom2NQxI+nDTYPkqzry5yb0YnNMM39WUJXgj4aqFEWlueFfgu2OTRrGF4TZx4MNDuBQ68eJbx06RTnUGGSHdLUX7gCPPkoNR0zhlTZPpUoLuGML7Np4kkzZk7N43YoNIoCYUMQLLjaJPG7jBjQNP+vremNLRqUO1iuB3udhTg2TF2KdG2BXh7GWXcBPZloGZAWozPQWLyleW5fhMHNDHwwIms=
  app: serene-anchorage-43988
  on:
    repo: KLlorente/Blog-API
